# Generated by Django 2.0.7 on 2018-07-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire_ta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descvariable',
            name='code',
        ),
        migrations.RemoveField(
            model_name='descvariable',
            name='description',
        ),
        migrations.RemoveField(
            model_name='descvariable',
            name='millesime',
        ),
        migrations.RemoveField(
            model_name='descvariable',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='descvariable',
            name='table_var_associee',
        ),
        migrations.RemoveField(
            model_name='descvariable',
            name='valeur',
        ),
        migrations.RemoveField(
            model_name='descvariable',
            name='var_associee',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='modalites',
        ),
    ]
