# Generated by Django 2.0.7 on 2018-07-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire_ta', '0002_auto_20180725_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescVariable',
        ),
    ]
