# Generated by Django 2.0.7 on 2018-07-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire_ta', '0003_delete_descvariable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='doc',
            new_name='formule_ini',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='fiabilite',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='lgr',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='millesime',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='nat',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='origine',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='type',
        ),
    ]
