# Generated by Django 2.0.7 on 2018-07-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire_ta', '0007_remove_variable_origine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='nature',
            new_name='origne',
        ),
    ]
