# Generated by Django 2.0.7 on 2018-07-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire_ta', '0008_auto_20180728_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='nature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
