# Generated by Django 2.0.7 on 2018-07-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire_ta', '0009_variable_nature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='origne',
            new_name='origine',
        ),
    ]
