# Generated by Django 2.0.7 on 2018-08-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire_ta', '0012_variable_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste', models.CharField(blank=True, max_length=2550, null=True)),
                ('table', models.CharField(blank=True, max_length=2550, null=True)),
            ],
        ),
    ]
