# Generated by Django 2.1 on 2018-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire_ta', '0013_ordretables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
