# Generated by Django 2.0.7 on 2018-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descvariable',
            name='var_associee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
