# Generated by Django 2.0.7 on 2018-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0002_descvariable_var_associee'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
