# Generated by Django 2.0.7 on 2018-07-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0005_auto_20180719_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='descvariable',
            name='table_var_associee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
