# Generated by Django 2.0.7 on 2018-08-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0006_descvariable_table_var_associee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='nature',
        ),
    ]
