# Generated by Django 2.0.7 on 2018-08-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0007_remove_variable_nature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='description',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='fiabilite',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='lgr',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='millesime',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='modalites',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='nat',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='origine',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='table_associee',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='type',
        ),
    ]
