# Generated by Django 2.0.7 on 2018-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0009_auto_20180801_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='millesime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
