# Generated by Django 2.0.7 on 2018-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0010_auto_20180801_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_test', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='variable',
            name='modalites',
            field=models.ManyToManyField(blank=True, to='dictionnaire.DescVariable'),
        ),
    ]
