# Generated by Django 2.0.7 on 2018-08-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0011_auto_20180809_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
