# Generated by Django 2.0.7 on 2018-08-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0012_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordre_variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TUP', models.CharField(blank=True, max_length=255, null=True)),
                ('pnb10_parcelle', models.CharField(blank=True, max_length=255, null=True)),
                ('pb0010_local', models.CharField(blank=True, max_length=255, null=True)),
                ('proprietaire_droit', models.CharField(blank=True, max_length=255, null=True)),
                ('lots_locaux', models.CharField(blank=True, max_length=255, null=True)),
                ('pb21_pev', models.CharField(blank=True, max_length=255, null=True)),
                ('pb30_pevexoneration', models.CharField(blank=True, max_length=255, null=True)),
                ('pb36_pevtaxation', models.CharField(blank=True, max_length=255, null=True)),
                ('pb40_pevprincipale', models.CharField(blank=True, max_length=255, null=True)),
                ('pb50_pevprofessionnelle', models.CharField(blank=True, max_length=255, null=True)),
                ('pb60_pevdependances', models.CharField(blank=True, max_length=255, null=True)),
                ('pdl10_pdl', models.CharField(blank=True, max_length=255, null=True)),
                ('pdl20_parcellecomposante', models.CharField(blank=True, max_length=255, null=True)),
                ('pdl30_lots', models.CharField(blank=True, max_length=255, null=True)),
                ('pnb21_suf', models.CharField(blank=True, max_length=255, null=True)),
                ('pnb30_sufexoneration', models.CharField(blank=True, max_length=255, null=True)),
                ('pnb36_suftaxation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
