# Generated by Django 2.0.7 on 2018-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0013_ordre_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordre_variable',
            name='TUP',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='lots_locaux',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pb0010_local',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pb21_pev',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pb30_pevexoneration',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pb36_pevtaxation',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pb40_pevprincipale',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pb50_pevprofessionnelle',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pb60_pevdependances',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pdl10_pdl',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pdl20_parcellecomposante',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pdl30_lots',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pnb10_parcelle',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pnb21_suf',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pnb30_sufexoneration',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='pnb36_suftaxation',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordre_variable',
            name='proprietaire_droit',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
