# Generated by Django 2.0.7 on 2018-08-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0014_auto_20180810_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordre_variable',
            new_name='OrdreTables',
        ),
    ]
