# Generated by Django 2.0.7 on 2018-08-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0015_auto_20180810_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordretables',
            old_name='TUP',
            new_name='liste',
        ),
        migrations.RenameField(
            model_name='ordretables',
            old_name='lots_locaux',
            new_name='table',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pb0010_local',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pb21_pev',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pb30_pevexoneration',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pb36_pevtaxation',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pb40_pevprincipale',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pb50_pevprofessionnelle',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pb60_pevdependances',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pdl10_pdl',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pdl20_parcellecomposante',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pdl30_lots',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pnb10_parcelle',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pnb21_suf',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pnb30_sufexoneration',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='pnb36_suftaxation',
        ),
        migrations.RemoveField(
            model_name='ordretables',
            name='proprietaire_droit',
        ),
    ]
